### ISSUE TITLE
Crash on startup with Immersive Portals

### ISSUE THREAD

**Issue by Legomountain14** [DrexHD/Vanish#13]
## Description:
When I run the server jar, it tries to start, but it crashes with a "Mixin apply" error. 
## Installed Mods:
- fabric-api-0.76.0+1.19.2.jar
- immersive-portals-2.3.2-mc1.19.2-fabric.jar
- vanish-1.3.2.jar

I hope this is an easy fix!

## Full Log:

> Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
> [14:34:38] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.19
> [14:34:38] [main/INFO]: Loading 53 mods:
> 	- fabric-api 0.76.0+1.19.2
> 	   |-- fabric-api-base 0.4.15+8f4e8eb390
> 	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
> 	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
> 	   |-- fabric-block-api-v1 1.0.2+e415d50e90
> 	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
> 	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
> 	   |-- fabric-command-api-v1 1.2.16+f71b366f90
> 	   |-- fabric-command-api-v2 2.2.1+413cbbc790
> 	   |-- fabric-commands-v0 0.2.33+df3654b390
> 	   |-- fabric-containers-v0 0.1.41+df3654b390
> 	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
> 	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
> 	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
> 	   |-- fabric-data-generation-api-v1 5.3.8+413cbbc790
> 	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
> 	   |-- fabric-entity-events-v1 1.5.4+9244241690
> 	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
> 	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
> 	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
> 	   |-- fabric-item-api-v1 1.6.6+b7d1888890
> 	   |-- fabric-item-groups-v0 0.3.39+9244241690
> 	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
> 	   |-- fabric-keybindings-v0 0.2.23+df3654b390
> 	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
> 	   |-- fabric-loot-api-v2 1.1.13+83a8659290
> 	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
> 	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
> 	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
> 	   |-- fabric-models-v0 0.3.21+c6af733c90
> 	   |-- fabric-networking-api-v1 1.2.11+10eb22f490
> 	   |-- fabric-networking-v0 0.3.28+df3654b390
> 	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
> 	   |-- fabric-particles-v1 1.0.14+4d0d570390
> 	   |-- fabric-recipe-api-v1 1.0.1+413cbbc790
> 	   |-- fabric-registry-sync-v0 0.9.32+9244241690
> 	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
> 	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
> 	   |-- fabric-renderer-registries-v1 3.2.24+df3654b390
> 	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
> 	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
> 	   |-- fabric-rendering-v0 1.1.27+df3654b390
> 	   |-- fabric-rendering-v1 1.12.1+d8ef690890
> 	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
> 	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
> 	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
> 	   |-- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90
> 	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
> 	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
> 	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
> 	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
> 	- fabricloader 0.14.19
> 	- immersive_portals 2.3.2
> 	   |-- cloth-config 8.0.75
> 	   |    \-- cloth-basic-math 0.6.1
> 	   |-- imm_ptl_core 2.3.1
> 	   \-- q_misc_util 2.3.1
> 	- java 17
> 	- melius-vanish 1.3.2
> 	   |-- com_github_llamalad7_mixinextras 0.1.1
> 	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
> 	   |-- placeholder-api 2.0.0-beta.7+1.19
> 	   |-- player-data-api 0.2.1+1.19
> 	   \-- server_translations_api 1.4.17+1.19.2
> 	        \-- packet_tweaker 0.3.0+1.18.2
> 	- minecraft 1.19.2
> [14:34:39] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Users/oliverbult/Desktop/Testing%20server/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
> [14:34:39] [main/INFO]: Compatibility level set to JAVA_16
> [14:34:39] [main/INFO]: Compatibility level set to JAVA_17
> [14:34:45] [main/INFO]: Building unoptimized datafixer
> [14:34:48] [main/INFO]: Loading Immersive Portals config
> [14:34:48] [main/INFO]: IP Config Applied
> [14:34:48] [main/INFO]: Immersive Portals Mod Initializing
> [14:34:48] [main/INFO]: Dimensional Threading is not present
> [14:34:48] [main/INFO]: Pehkui is not present
> [14:34:48] [main/INFO]: Gravity API is not present
> [14:34:48] [main/INFO]: Loading configuration...
> [14:34:48] [main/WARN]: You specified a resource pack without providing a sha1 hash. Pack will be updated on the client only if you change the name of the pack.
> [14:34:48] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
> [14:34:51] [ForkJoinPool.commonPool-worker-1/ERROR]: Non [a-z0-9/._-] character in path of location: server_translations_api:lang/et_EE.json
> [14:34:52] [main/INFO]: Loaded 7 recipes
> [14:34:52] [main/INFO]: Loaded 1179 advancements
> [14:34:52] [ForkJoinPool.commonPool-worker-1/INFO]: Loaded 5443 translation keys
> [14:34:54] [main/ERROR]: Mixin apply for mod melius-vanish failed vanish.mixins.json:PlayerListMixin from mod melius-vanish -> net.minecraft.class_3324: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_3324::vanish_hideGameEvents with priority 1000 cannot inject into net/minecraft/class_3324::method_14605(Lnet/minecraft/class_1657;DDDDLnet/minecraft/class_5321;Lnet/minecraft/class_2596;)V merged by qouteall.imm_ptl.core.mixin.common.other_sync.MixinPlayerList with priority 1000 [PREINJECT Applicator Phase -> vanish.mixins.json:PlayerListMixin from mod melius-vanish -> Prepare Injections ->  -> wrapWithCondition$zjc000$melius-vanish$vanish_hideGameEvents(Lnet/minecraft/class_3244;Lnet/minecraft/class_2596;Lnet/minecraft/class_1657;)Z -> Prepare]
> org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_3324::vanish_hideGameEvents with priority 1000 cannot inject into net/minecraft/class_3324::method_14605(Lnet/minecraft/class_1657;DDDDLnet/minecraft/class_5321;Lnet/minecraft/class_2596;)V merged by qouteall.imm_ptl.core.mixin.common.other_sync.MixinPlayerList with priority 1000 [PREINJECT Applicator Phase -> vanish.mixins.json:PlayerListMixin from mod melius-vanish -> Prepare Injections ->  -> wrapWithCondition$zjc000$melius-vanish$vanish_hideGameEvents(Lnet/minecraft/class_3244;Lnet/minecraft/class_2596;Lnet/minecraft/class_1657;)Z -> Prepare]
> 	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at com.llamalad7.mixinextras.injector.WrapWithConditionInjectionInfo.prepare(WrapWithConditionInjectionInfo.java:33) ~[com_github_llamalad7_mixinextras-0.1.1-963eedbd46d46d76.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.19.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
> 	at net.minecraft.server.Main.method_29734(Main.java:211) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:264) [server-intermediary.jar:?]
> 	at net.minecraft.server.Main.main(Main.java:210) [server-intermediary.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.19.jar:?]
> 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.19.jar:?]
> 	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-launch.jar:0.11.2]
> [14:34:54] [main/ERROR]: Failed to start the minecraft server
> java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3324 failed
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.19.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
> 	at net.minecraft.server.Main.method_29734(Main.java:211) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:264) ~[server-intermediary.jar:?]
> 	at net.minecraft.server.Main.main(Main.java:210) [server-intermediary.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.19.jar:?]
> 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.19.jar:?]
> 	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-launch.jar:0.11.2]
> Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.19.jar:?]
> 	... 12 more
> Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [vanish.mixins.json:PlayerListMixin from mod melius-vanish] from phase [DEFAULT] in config [vanish.mixins.json] FAILED during APPLY
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.19.jar:?]
> 	... 12 more
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_3324::vanish_hideGameEvents with priority 1000 cannot inject into net/minecraft/class_3324::method_14605(Lnet/minecraft/class_1657;DDDDLnet/minecraft/class_5321;Lnet/minecraft/class_2596;)V merged by qouteall.imm_ptl.core.mixin.common.other_sync.MixinPlayerList with priority 1000 [PREINJECT Applicator Phase -> vanish.mixins.json:PlayerListMixin from mod melius-vanish -> Prepare Injections ->  -> wrapWithCondition$zjc000$melius-vanish$vanish_hideGameEvents(Lnet/minecraft/class_3244;Lnet/minecraft/class_2596;Lnet/minecraft/class_1657;)Z -> Prepare]
> 	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at com.llamalad7.mixinextras.injector.WrapWithConditionInjectionInfo.prepare(WrapWithConditionInjectionInfo.java:33) ~[com_github_llamalad7_mixinextras-0.1.1-963eedbd46d46d76.jar:?]
> 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.19.jar:?]
> 	... 12 more

## Or:
[latest.log](https://github.com/DrexHD/Vanish/files/11536339/latest.log)

**Comment by Legomountain14** [comment]
I thought would be helpful to report this bug, but it is OK if you don't support 1.19.2 anymore.

**Comment by DrexHD** [comment]
I have now released version [1.4.1](https://github.com/DrexHD/Vanish/releases/tag/v1.4.1-1.19.4) for 1.19.4, which works around this issue. For full compatibility the linked PR needs to be merged, read it for further information.
PS: I don't plan to backport this fix to any other version, as it also requires changes from Immersive Portals!
