### ISSUE TITLE
Vanished players are counted towards online players in Styled Player List

### ISSUE THREAD

**Issue by JumperCzech** [DrexHD/Vanish#2]
![image](https://user-images.githubusercontent.com/83337894/192591741-7ca19873-5d9d-4a5d-ba54-40bb40fa1877.png)

2 players and 1 that is vanished shows as "3"

https://modrinth.com/mod/styledplayerlist

**Comment by DrexHD** [comment]
Change the placeholder in `./config/styledplayerlist/styles/<style>.json` from `%server:online%` to `%vanish:online%`

**Comment by DrexHD** [comment]
I should probably also add that it will still display as 3 for you (see: [placeholders](https://github.com/DrexHD/Vanish#placeholders), because you can see yourself), but everyone else that doesn't have `vanish.feature.view` [permission](https://github.com/DrexHD/Vanish#permissions) will see 2.

**Comment by JumperCzech** [comment]
ok thanku
