### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Nicolol1234** [DrexHD/Vanish#27]
when i join the server, the server crash, here is the crash report:

https://mclo.gs/TYem7Gb

**Comment by DrexHD** [comment]
Are you sure the crash is caused by this mod? This mod conditionally cancels join and leave messages, but this doesn't seem to be the problem here!

**Comment by Nicolol1234** [comment]
I'll see

**Comment by Nicolol1234** [comment]
Found what's happening it's another mod who is messing up with everything. No clue of which mod it is in all of the crash report it produce, rly weird
