### ISSUE TITLE
Could you add compatibility with the McBot mod for the Vanish mod?

### ISSUE THREAD

**Issue by A0000Xz** [DrexHD/Vanish#35]
I am using the latest module version 1.5.2 and Minecraft version 1.20.1
The cause of the incident originated from the fact that the McBot module forwards in-game messages to the chat software's group chat
But the McBot mod will ignore the effect of the vanish mod, and issuing a list command in group chat will list the vanished players.
Not only that, fake online and offline messages sent by the Vanish mod will be ignored by the McBot mod and McBot will only forward real online and offline messages.This will expose the fact of using vanish.
I roughly checked and thought it might be that McBot and Vanish used the same three mixins.But I don't have any solutions either.
Oh,by the way, actually I also want to ask, how do I use the meta key "vanish_on_join"?
Sorry to trouble you again.

**Comment by DrexHD** [comment]
> I am using the latest module version 1.5.2 and Minecraft version 1.20.1
The cause of the incident originated from the fact that the McBot module forwards in-game messages to the chat software's group chat
But the McBot mod will ignore the effect of the vanish mod, and issuing a list command in group chat will list the vanished players.
Not only that, fake online and offline messages sent by the Vanish mod will be ignored by the McBot mod and McBot will only forward real online and offline messages.This will expose the fact of using vanish.
I roughly checked and thought it might be that McBot and Vanish used the same three mixins.But I don't have any solutions either.

Compatibility with discord mods needs to implemented manually (usually by the discord mods).
See: https://github.com/Reimnop/Discord4Fabric/pull/104, https://github.com/QuiltServerTools/BlockBot/pull/53, https://github.com/hypherionmc/sdlink/commit/cca26466b7a34c6e9ad0abe505e886fc90b45bfb or https://github.com/irunatbullets/DisFabric/commit/0aa1e20cc70fc7886321dd6194dddc6084a8421f

>  Oh,by the way, actually I also want to ask, how do I use the meta key "vanish_on_join"?

The only mod that currently supports meta keys from the permission api is luckperms. To add the key to a player run `/lp user <name> meta set vanish_on_join true`
