### ISSUE TITLE
Conflict with MiniMOTD Reforged.

### ISSUE THREAD

**Issue by CongYuSanXun** [DrexHD/Vanish#36]
Once Vanish is loaded on the server, MiniMOTD Reforged will fail.
The server motd will restore its original appearance.
MiniMOTD Reforged：https://modrinth.com/mod/minimotd-reforged

**Comment by DrexHD** [comment]
This mod works with the original [minimotd](https://modrinth.com/plugin/minimotd) mod. If you are experiencing issues with a port of that mod, to another loader, please report it to them. Forge is not officially supported by this mod anyways.
