### ISSUE TITLE
Better Sleeping player count for skip night

### ISSUE THREAD

**Issue by Kisuny** [DrexHD/Vanish#39]
[Better Sleeping](https://www.curseforge.com/minecraft/mc-mods/bettersleeping-revived) displays how many players are on the server for sleeping, thereby showing that someone is in vanisha. 

![image](https://github.com/DrexHD/Vanish/assets/56004431/d44f6b31-e841-4fd5-a7d9-e34f7ecfaec4)

**Comment by DrexHD** [comment]
Please report this on [Better Sleppings issue tracker](https://github.com/ReviversMC/bettersleeping/issues). This mod provides an [API for other mods](https://github.com/DrexHD/Vanish?tab=readme-ov-file#developers) like this to integrate.

**Comment by DrexHD** [comment]
Closing, because this needs to be resolved by the other mod.
