### ISSUE TITLE
Vanished players will prevent normal players from placing blocks.

### ISSUE THREAD

**Issue by A0000Xz** [DrexHD/Vanish#40]
vanish mod version:1.5.3-1.20.1
minecraft version:1.20.1
I noticed that the disappearing player actually prevented the player from placing blocks in a server.
Of course, I know we already have mod version 1.5.4, but I don't have time to test it now, so let me mention it first.
Additionally, I noticed that some people seem to be creating mods with anti-vanish functionality. However, after my experiments, it does not work on your mod, but I heard it can be used to reverse some plugin versions.So, is there a possibility of this mod becoming ineffective? I guess this mod will modify the packets sent by the server, so it should be invulnerable, right?

**Comment by DrexHD** [comment]
This mod removes and modifies the packets as if the vanishing player was not present on the server. So it's not possible for the client to get any information about the player. The only way to know *something* is missing "features" like this issue, but those can be added/patched ;)
