### ISSUE TITLE
TAB [NEZNAMY] Vanish Detection

### ISSUE THREAD

**Issue by Skullians** [DrexHD/Vanish#48]
Hey, does this mod have support for vanish detection in the TAB mod by NEZNAMY?
I've looked through TAB's 'vanish detection' wiki but can't make sense of it.

**Comment by DrexHD** [comment]
Can you link to the mentioned wiki section? Depending on what you need I can also recommend [styledplayerlist](https://modrinth.com/mod/styledplayerlist), which is better integrated into the fabric eco system and works well with this mod.

**Comment by Skullians** [comment]
> Can you link to the mentioned wiki section? Depending on what you need I can also recommend [styledplayerlist](https://modrinth.com/mod/styledplayerlist), which is better integrated into the fabric eco system and works well with this mod.

https://github.com/NEZNAMY/TAB/wiki/Additional-information#vanish-detection

**Comment by Skullians** [comment]
I have messed around with styledplayerlist before, but used TAB because it integrates nicer with LP and is arguably better in terms of functionality and configurability.

**Comment by Skullians** [comment]
Damn.
I'll make a GitHub issue with TAB and see what they say.
Thanks for your time.

**Comment by Skullians** [comment]
Hey @DrexHD I've moved over to styledplayerlist.
Just to check, StyledPlayerList should work without any extra configs for vanish?
I'm using the latest 1.19.2 StyledPlayerChat mod for Fabric if that matters.

I've done /vanish and I can still see myself in TAB but i'm assuming that's because I'm the one in vanish LOL

**Comment by DrexHD** [comment]
Yeah, you can always see yourself. There is only one thing you need to change for them to work perfectly together: Replace any placeholder `%server:online%` with `%vanish:online%`
