### ISSUE TITLE
Vanish ourselves through server console before in-game login

### ISSUE THREAD

**Issue by HoustonLFB** [DrexHD/Vanish#49]
Hello, here's an idea i just got.

Being able to vanish ourselves via /vanish Username in the server console before logging so no one can know i joined the server and then made myself vanish fake-leave.

**Comment by DrexHD** [comment]
Hey, this is already a feature. You can use `/vanish on <name>` and `/vanish off <name>` to change vanish status. There is also `vanish_on_join` [meta key](https://github.com/DrexHD/Vanish?tab=readme-ov-file#meta-keys)!
