### ISSUE TITLE
Players Can Attack And Kill Vanished Players

### ISSUE THREAD

**Issue by Marioiscool246** [DrexHD/Vanish#50]
Title is self explanatory.

**Comment by DrexHD** [comment]
It's not very self explanatory imo. How do you attack players you don't see? FYI vanished players are not intended to be invulnerable to indirect damage like creeper explosions.

**Comment by Marioiscool246** [comment]
One possible instance can be caused by latency
Player uses /vanish to escape another player that is about to attack them
Other player successfully attacks the player before they disappear, killing them while in vanish
