### ISSUE TITLE
[BUG/INCOMPATIBILITY] List of Players doesn´t remove the vanished player on Fabric 1.21.1 with StyledTabList installed

### ISSUE THREAD

**Issue by NextRaven10** [DrexHD/Vanish#53]
As the title says...
Here is the view of the operator:
![grafik](https://github.com/user-attachments/assets/2b9614ba-3929-4d44-8f84-c42b9c951600)
and here is the view of a normal player while I´m still in vanish:
![grafik](https://github.com/user-attachments/assets/ceceea79-171f-4241-b331-60b65a708cd5)
As you can see the number at the top doesn´t update :/

Let me know if I can provide any more information that might help to fix the bug :)

**Comment by DrexHD** [comment]
You need to replace the placeholder. Change `%server:online%` to `%vanish:online%`!
