### ISSUE TITLE
(Feature Request) Add Compatibility with DisFabric

### ISSUE THREAD

**Issue by TwoPointInfinity** [DrexHD/Vanish#6]
I tried reaching out to the makers of disfabric but havent heard back. 
Not sure who would be able to work with the other but when using disfabric https://github.com/BRForgers/DisFabric the discord channel still notifies when vanished players join or leave and also do not receive the fake join and leave messages.

**Comment by TwoPointInfinity** [comment]
also disfabric allows the command "!online" to see the player list from discord, this will also list vanished players.

**Comment by DrexHD** [comment]
This would need to be resolved by in DisFabric source code, by using the [Vanish API to check if a user is vanished](https://github.com/DrexHD/Vanish/blob/1.19.3/stable/src/main/java/me/drex/vanish/api/VanishAPI.java#L27). If you need a discord <-> minecraft bridge with vanish support, you could use [BlockBot](https://github.com/QuiltServerTools/BlockBot/tree/rewrite)!

**Comment by TwoPointInfinity** [comment]
Thank you so much! <3

**Comment by TwoPointInfinity** [comment]
> This would need to be resolved by in DisFabric source code, by using the [Vanish API to check if a user is vanished](https://github.com/DrexHD/Vanish/blob/1.19.3/stable/src/main/java/me/drex/vanish/api/VanishAPI.java#L27). If you need a discord <-> minecraft bridge with vanish support, you could use [BlockBot](https://github.com/QuiltServerTools/BlockBot/tree/rewrite)!

Do you have a working version of blockbot for 1.19.2? I cant figure out how to do the files for minecraft version, fabric loader version, yarn mappings.. I am so desperately trying to change what i need to change so i can do gradle build and upload it to my server. I was hoping to have it for 1.19.2 before we move to 1.19.3, i still need to wait on 1 more to update until we can update. I tried a few different forks whereits only a commit or 2 behind and it wont work for me. it will either fail to build or fail to run on the server.

**Comment by DrexHD** [comment]
You can use this [action build](https://github.com/DrexHD/BlockBot/actions/runs/3603332335), which should work on 1.19.2!

**Comment by TwoPointInfinity** [comment]
If this is an appropriate place as any, while setting up blockbot i am using required linking and i have set the required role on line 134 to the role of the discord group that i want players to have to need to get linked and join. But players with this role are unable to do /link. I am able to use it though, i believe because i am the manager of the discord server. 
I also have no idea what the "syncedRoles = {}" on line 136 is supposed to look like, i want to use it. I already gave players the permissions they need in game. 
Does this area of the config look right to you? I have double checked the role ID and it is correct.
`[Linking]
# Enable account linking between Minecraft and discord. Enables /link in game and in discord
enabled = true
# Requires a linked account to join (Like a whitelist) Shows linking code on disconnect screen
requireLinking = true
# Sync the linked users discord nickname to their minecraft username
nicknameSync = true
# Comma seperated list of role ID's allowed to join the server. Leave blank to allow any linked account to join. Also restricts /link command in discord
requiredRoles = [1049088965816373295]
# A map of role ID's and minecraft group ID's. Syncs roles if the player has blockbot.sync.<group_id> permission
syncedRoles = {}
# Require linked players to be in the main discord
requireInServer = true`

**Comment by DrexHD** [comment]
I don't think this is the appropriate place for this, for blockbot support join their [discord server](https://discord.gg/rz2CCPhbMA)!
I should note however that `syncedRoles` is broken in the linked build (it's missing the commit https://github.com/QuiltServerTools/BlockBot/commit/a67ffd968b0efdb56c737a6b0b5dafd037d4e86f)!
